<?php
require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

$Timestamp = date("Y-m-d H:i:s");
$User = "Username";
$PostID = "89";
$CommentID = "123";
$Status = "Deleted";
$CommentDescription = "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
$Admin = "Admin";
$Email = "Admin@gmail.com";

// Document Header
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Comment Logs', 0, 1, 'C');
$pdf->Cell(189, 5, '', 0, 1, 'L');

// Audit Trail Information
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'Report Generated By: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Admin, 0, 1, 'L');

$pdf->Cell(60, 10, 'Generation Timestamp: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Timestamp, 0, 1, 'L');

$pdf->Cell(60, 10, 'Administrator Email: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Email, 0, 1, 'L');
$pdf->Cell(189, 10, '', 0, 1, 'L');

// Table Section Title
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);
$pdf->Cell(189, 5, '', 0, 1, 'L');

// Table Header
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(50, 10, 'Timestamp', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'User', 1, 0, 'C', true);
$pdf->Cell(25, 10, 'Post ID', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Comment ID', 1, 0, 'C', true);
$pdf->Cell(54, 10, 'Comment Description', 1, 1, 'C', true);

// Row Data
$pdf->SetFont('Arial', '', 12);
$x = $pdf->GetX();
$y = $pdf->GetY();
$lineHeight = 6;

// Print MultiCell first to get height
$pdf->SetXY($x + 50 + 30 + 25 + 30, $y);
$pdf->MultiCell(54, $lineHeight, $CommentDescription, 1, 'J');
$descHeight = $pdf->GetY() - $y;

// Draw other cells with same height
$pdf->SetXY($x, $y);
$pdf->Cell(50, $descHeight, $Timestamp, 1, 0, 'C');
$pdf->Cell(30, $descHeight, $User, 1, 0, 'C');
$pdf->Cell(25, $descHeight, $PostID, 1, 0, 'C');
$pdf->Cell(30, $descHeight, $CommentID, 1, 0, 'C');
// Description already drawn

$pdf->Output();
?>
