<?php
include("../../php/db_conn.php"); 
session_start();

require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();


$account_id = $_SESSION['account_id'];
$email = "No email";

if ($account_id) {
    $sql = "SELECT email from student_tb WHERE account_id = '$account_id'";
    $emailResult = mysqli_query($conn, $sql);

    if ($emailResult && mysqli_num_rows($emailResult) > 0) {
        $row = mysqli_fetch_assoc($emailResult);
        $email = $row['email'];
    }
}

// Static values for the admin, modify these based on your system
$Admin = "Admin";
$Email = $email;  // Replace with dynamic logic if needed
$Timestamp = date("Y-m-d H:i:s");

// Document Header
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Comment Logs', 0, 1, 'C');
$pdf->Cell(189, 5, '', 0, 1, 'L');

// Audit Trail Information
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'Report Generated By: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Admin, 0, 1, 'L');

$pdf->Cell(60, 10, 'Generation Timestamp: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Timestamp, 0, 1, 'L');

$pdf->Cell(60, 10, 'Administrator Email: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Email, 0, 1, 'L');
$pdf->Cell(189, 10, '', 0, 1, 'L');

// Table Section Title
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);
$pdf->Cell(189, 5, '', 0, 1, 'L');

// Table Header (Reduced width for Post ID and Account ID)
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(40, 10, 'Timestamp', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Post ID', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Account ID', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Comment ID', 1, 0, 'C', true);
$pdf->Cell(59, 10, 'Comment Description', 1, 1, 'C', true);

// Row Data (Fetching from your query result)
$getCommentsAudit = "
    SELECT 
        comment_tb.created_at, 
        comment_tb.post_id, 
        comment_tb.account_id, 
        comment_tb.comment_id, 
        comment_tb.comment_desc
    FROM comment_tb
    ORDER BY comment_tb.created_at DESC
";

$result = mysqli_query($conn, $getCommentsAudit);

$pdf->SetFont('Arial', '', 12);
$lineHeight = 6;

if ($result && mysqli_num_rows($result) > 0) {
    while ($row = mysqli_fetch_assoc($result)) {
        $timestamp = $row['created_at'];
        $postId = $row['post_id'];
        $accountId = $row['account_id'];
        $commentId = $row['comment_id'];
        $description = $row['comment_desc'];

        // Save current X and Y for reference
        $x = $pdf->GetX();
        $y = $pdf->GetY();

        // Print regular cells first (Timestamp, Post ID, Account ID, Comment ID)
        $pdf->Cell(40, $lineHeight, $timestamp, 1, 0, 'C');
        $pdf->Cell(30, $lineHeight, $postId, 1, 0, 'C');
        $pdf->Cell(30, $lineHeight, $accountId, 1, 0, 'C');
        $pdf->Cell(30, $lineHeight, $commentId, 1, 0, 'C');

        // Print MultiCell for description
        $pdf->SetXY($x + 40 + 30 + 30 + 30, $y); // Adjusted X position for description column
        $pdf->MultiCell(59, $lineHeight, $description, 1, 'J');
        
        // Update the Y-position after MultiCell to account for varying row heights
        $descHeight = $pdf->GetY() - $y;
        $pdf->SetXY($x, $y + $descHeight); // Adjust Y for the next row
    }
} else {
    $pdf->Cell(189, 10, 'No comment logs available.', 1, 1, 'C');
}

$pdf->Output();
?>
