<?php
session_start();
include("../../php/db_conn.php"); 

$account_id = $_SESSION['account_id'];
$email = "No email";

if ($account_id) {
    $sql = "SELECT email from student_tb WHERE account_id = '$account_id'";
    $emailResult = mysqli_query($conn, $sql);

    if ($emailResult && mysqli_num_rows($emailResult) > 0) {
        $row = mysqli_fetch_assoc($emailResult);
        $email = $row['email'];
    }
}

// SQL query to fetch post logs
$getPostAudit = "
    SELECT 
        post_tb.created_at, 
        student_tb.username, 
        post_tb.post_id, 
        post_tb.title, 
        post_tb.description 
    FROM post_tb
    JOIN student_tb ON post_tb.account_id = student_tb.account_id
    ORDER BY post_tb.created_at DESC
";

$result = mysqli_query($conn, $getPostAudit);


require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

// Report metadata
$Timestamp = date("Y-m-d H:i:s");
$GeneratedBy = $_SESSION['username'];
$Email = $email;

// Title
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Post Logs', 0, 1, 'C');
$pdf->Ln(5);

// Audit Trail Information
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'Report Generated By:', 0, 0, 'L');
$pdf->Cell(129, 10, $GeneratedBy, 0, 1, 'L');

$pdf->Cell(60, 10, 'Generation Timestamp:', 0, 0, 'L');
$pdf->Cell(129, 10, $Timestamp, 0, 1, 'L');

$pdf->Cell(60, 10, 'Administrator Email:', 0, 0, 'L');
$pdf->Cell(129, 10, $Email, 0, 1, 'L');
$pdf->Ln(5);

// Logs Section
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);
$pdf->Ln(5);

// Table Headers
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(45, 10, 'Timestamp', 1, 0, 'C', true);
$pdf->Cell(35, 10, 'Username', 1, 0, 'C', true);
$pdf->Cell(40, 10, 'Title', 1, 0, 'C', true);
$pdf->Cell(20, 10, 'Post ID', 1, 0, 'C', true);
$pdf->Cell(50, 10, 'Description', 1, 1, 'C', true);

// Table Rows
$pdf->SetFont('Arial', '', 12);
while ($row = mysqli_fetch_assoc($result)) {
    $lineHeight = 6;

    // Save current position
    $x = $pdf->GetX();
    $y = $pdf->GetY();

    // Calculate height needed for each multicell field
    $pdf->SetXY($x + 45 + 35, $y); // title position
    $pdf->MultiCell(40, $lineHeight, $row['title'], 0, 'L');
    $titleHeight = $pdf->GetY() - $y;

    $pdf->SetXY($x + 45 + 35 + 40 + 20, $y); // description position
    $pdf->MultiCell(50, $lineHeight, $row['description'], 0, 'L');
    $descHeight = $pdf->GetY() - $y;

    // Get max height for the row
    $rowHeight = max($titleHeight, $descHeight, $lineHeight);

    // Reset position and draw cells
    $pdf->SetXY($x, $y);
    $pdf->Cell(45, $rowHeight, $row['created_at'], 1, 0, 'C');
    $pdf->Cell(35, $rowHeight, $row['username'], 1, 0, 'C');

    // Re-draw Title MultiCell with border
    $pdf->SetXY($x + 45 + 35, $y);
    $pdf->MultiCell(40, $lineHeight, $row['title'], 1, 'L');

    // Because MultiCell moves cursor, reset X and Y again
    $pdf->SetXY($x + 45 + 35 + 40, $y);
    $pdf->Cell(20, $rowHeight, $row['post_id'], 1, 0, 'C');

    $pdf->SetXY($x + 45 + 35 + 40 + 20, $y);
    $pdf->MultiCell(50, $lineHeight, $row['description'], 1, 'L');

    // Move to the next line (below the tallest cell)
    $pdf->SetY($y + $rowHeight);
}


$pdf->Output();
?>
