<?php
require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

$Timestamp = date("Y-m-d H:i:s");
$User = "Username";
$Title = "New Post";
$Description = "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
$Images = 3;


$Admin = "Admin";
$Email = "Admin@gmail.com";

// Title
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Post Logs', 0, 1, 'C');

$pdf->Cell(189, 5, '', 0, 1, 'L');

$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);


$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(60, 10, 'Report Generated By: ', 0, 0, 'L');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(129, 10, $Admin, 0, 1, 'L');

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(60, 10, 'Generation Timestamp: ', 0, 0, 'L');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(129, 10, $Timestamp, 0, 1, 'L');

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(60, 10, 'Administrator Email: ', 0, 0, 'L');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(129, 10, $Email, 0, 1, 'L');

$pdf->Cell(189, 10, '', 0, 1, 'L');




$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);

$pdf->Cell(189, 5, '', 0, 1, 'L');

// Header
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(45, 10, 'Timestamp', 1, 0, 'C',true);
$pdf->Cell(35, 10, 'User', 1, 0, 'C',true);
$pdf->Cell(40, 10, 'Title', 1, 0, 'C',true);
$pdf->Cell(20, 10, 'Images', 1, 0, 'C',true);
$pdf->Cell(50, 10, 'Description', 1, 1, 'C',true);

// Row data
$pdf->SetFont('Arial', '', 12);

// Save current X and Y
$x = $pdf->GetX();
$y = $pdf->GetY();
$lineHeight = 6;

// Print the first four columns (Timestamp, User, Title, Images)


// Now, print the Description (use MultiCell to allow wrapping)
$pdf->SetXY($x + 45 + 35 + 40 + 20, $y); // Move to the starting point of Description
$pdf->MultiCell(50, $lineHeight, $Description, 1, 'J');

// Calculate the height the Description has taken
$descHeight = $pdf->GetY() - $y; // How tall the Description cell became

// Reset Y position back to the start of the row for other cells
$pdf->SetXY($x, $y); 
$pdf->Cell(45, $descHeight, $Timestamp, 1, 0, 'C');
$pdf->Cell(35, $descHeight, $User, 1, 0, 'C');
$pdf->Cell(40, $descHeight, $Title, 1, 0, 'C');
$pdf->Cell(20, $descHeight, $Images, 1, 0, 'C');

// Description is already printed with MultiCell

$pdf->Output();
?>
