<?php
require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

$Timestamp = date("Y-m-d H:i:s");
$User = "Username";
$PostID = "1";
$Status = "Deleted";
$Reason = "Post contained inappropriate content due to violation of community guidelines. Please refer to the moderation policy.";

$Admin = "Admin";
$Email = "Admin@gmail.com";

// Header
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Delete Post Logs', 0, 1, 'C');
$pdf->Cell(189, 5, '', 0, 1, 'L');

$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'Report Generated By: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Admin, 0, 1, 'L');

$pdf->Cell(60, 10, 'Generation Timestamp: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Timestamp, 0, 1, 'L');

$pdf->Cell(60, 10, 'Administrator Email: ', 0, 0, 'L');
$pdf->Cell(129, 10, $Email, 0, 1, 'L');
$pdf->Cell(189, 10, '', 0, 1, 'L');

// Table Title
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);
$pdf->Cell(189, 5, '', 0, 1, 'L');

// Table Header
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(50, 10, 'Timestamp', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'User', 1, 0, 'C', true);
$pdf->Cell(25, 10, 'Post ID', 1, 0, 'C', true);
$pdf->Cell(25, 10, 'Status', 1, 0, 'C', true);
$pdf->Cell(59, 10, 'Reason for Deletion', 1, 1, 'C', true);

// Row Data
$pdf->SetFont('Arial', '', 12);
$x = $pdf->GetX();
$y = $pdf->GetY();
$lineHeight = 6;

// Print MultiCell first to get height
$pdf->SetXY($x + 50 + 30 + 25 + 25, $y);
$pdf->MultiCell(59, $lineHeight, $Reason, 1, 'J');
$descHeight = $pdf->GetY() - $y;

// Draw other cells with same height
$pdf->SetXY($x, $y);
$pdf->Cell(50, $descHeight, $Timestamp, 1, 0, 'C');
$pdf->Cell(30, $descHeight, $User, 1, 0, 'C');
$pdf->Cell(25, $descHeight, $PostID, 1, 0, 'C');
$pdf->Cell(25, $descHeight, $Status, 1, 0, 'C');
// Description already drawn

$pdf->Output();
?>
