<?php
require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

$Timestamp = date("Y-m-d H:i:s");
$User = "Username with long name";
$PostID = "89";
$CommentID = "123";
$Status = "Deleted";
$CommentDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
$Admin = "Admin";
$Email = "Admin@gmail.com";

// Column widths
$colWidths = [
    'Timestamp' => 40,
    'User' => 30,
    'PostID' => 20,
    'CommentID' => 25,
    'Reason' => 74
];

// Document Header
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(189, 10, 'User Comment Logs', 0, 1, 'C');
$pdf->Ln(5);

// Audit Trail Info
$pdf->SetFillColor(230, 230, 230);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(189, 10, 'Audit Trail Information', 0, 1, 'L', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'Report Generated By:', 0, 0);
$pdf->Cell(129, 10, $Admin, 0, 1);

$pdf->Cell(60, 10, 'Generation Timestamp:', 0, 0);
$pdf->Cell(129, 10, $Timestamp, 0, 1);

$pdf->Cell(60, 10, 'Administrator Email:', 0, 0);
$pdf->Cell(129, 10, $Email, 0, 1);
$pdf->Ln(5);

// Logs Section
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetFillColor(230, 230, 230);
$pdf->Cell(189, 10, 'Logs', 0, 1, 'L', true);
$pdf->Ln(3);

// Table Header
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell($colWidths['Timestamp'], 10, 'Timestamp', 1, 0, 'C', true);
$pdf->Cell($colWidths['User'], 10, 'User', 1, 0, 'C', true);
$pdf->Cell($colWidths['PostID'], 10, 'Post ID', 1, 0, 'C', true);
$pdf->Cell($colWidths['CommentID'], 10, 'Comment ID', 1, 0, 'C', true);
$pdf->Cell($colWidths['Reason'], 10, 'Reason for Deletion', 1, 1, 'C', true);

// Row Data
$pdf->SetFont('Arial', '', 12);
$data = [$Timestamp, $User, $PostID, $CommentID, $CommentDescription];
$lineHeight = 6;

// Compute height of each cell using MultiCell off-page
$cellHeights = [];
foreach (array_values($colWidths) as $i => $w) {
    $x = $pdf->GetX();
    $y = $pdf->GetY();
    $pdf->SetXY(200, 200); // move off-page
    $pdf->MultiCell($w, $lineHeight, $data[$i], 0);
    $height = $pdf->GetY() - 200;
    $cellHeights[] = $height;
    $pdf->SetXY($x, $y); // restore
}
$maxHeight = max($cellHeights);

// Actual row drawing
$x = $pdf->GetX();
$y = $pdf->GetY();

foreach (array_values($colWidths) as $i => $w) {
    $pdf->SetXY($x, $y);
    $pdf->MultiCell($w, $lineHeight, $data[$i], 1, 'L');
    $x += $w;
}
$pdf->Ln($maxHeight);

$pdf->Output();
?>
